name: CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Print Git SHA
        run: echo $GITHUB_SHA
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build Application
        run: npm run build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-dist
          path: dist

  docker:
    needs: verify

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: react-dist
          path: downloaded-dist
      - name: Verify Artifact
        run: ls -R downloaded-dist
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            debabrata100/react-ci-demo:latest
            debabrata100/react-ci-demo:${{ github.sha }}

          cache-from: type=gha
          cache-to: type=gha,mode=max
 